<a href="https://colab.research.google.com/github/mrkimbab/DAP_/blob/main/lecture2_ipynb_w2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(0)

# NumPy Exercises!
Complete the solution code to have a desired output.

**[Caution!]** Not allow to use iteration, such as for-loop.





### 1-1. Create a 5×5 numpy array of all False boolean’s 
[ref] [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html)

In [ ]:
# Input
arr_size = (5, 5)

# Solution
bool_arr = ############################

np.full(arr_size, False, dtype=bool)

# Print
print(bool_arr)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


### 1-2. Create a 7×7 diagonal matrix with diagonal index as 3.
diagonal matrix: 2-D array with ones on the diagonal and zeros elsewhere. 
(hint, ref [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))

In [ ]:
# Input
size = 7

# Solution
np_arr = np.eye(size) # 이럼 처음부터 1 배열 부여 k 넣으면 k번째부터 배열부여

np.eye(size ,k=3)
# Print
print(np_arr)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


### 2. Extract even numbers from given `arr`

In [ ]:
# Input
arr = np.arange(35) # 35까지 들어간 배열을 만든다

# Solution
arr = arr[arr%2==0] #짝수 뽑기. 1로 하면 홀수 뽑기

# Print
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


### 3. Get the positions where elements of `a` and `b` match
(hint, refer [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html).)



In [ ]:
# Input
a = np.array([1, 7, 3, 2, 3, 5, 3, 4, 5, 8, 2, 6, 9])
b = np.array([1, 2, 10, 8, 3, 4, 9, 4, 9, 8, 5, 3, 5])

# Solution
# idx = np.where(False, False, True, False) # 이러면 2번 배열만 뱉음
idx = np.where(a==b)

# Print
print(idx)

(array([0, 4, 7, 9]),)


### 4. Find the median, standard deviation, average of iris's `sepallength` (1st column).

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
med, std, avg = np.median(sepallength), np.std(sepallength), np.average(sepallength)

# Print
print(med, std, avg)

5.8 0.8253012917851409 5.843333333333334


### 5. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.
(hint, refer [np.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html).)

In [ ]:
# Input
np.random.seed(50)
a = np.random.randint(0, 10, 10)
print('Array: ', a)

# Solution
## Create an all True array  #out 이란 배열을 만들어 죄다 true로 채운다
out = np.full(a.shape[0],True)

## Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1] #[1] 을 하지 않으면 요소 / 중복 순서가 뜸
print('test: ', unique_positions)
## Mark those positions as False
out[unique_positions] = False # out 배열의 중복되는 부분에, false를 채운다.

print('Duplicate entrie: ', out)

Array:  [0 0 1 4 6 5 6 6 5 2]
test:  [0 2 9 3 5 4]
Duplicate entrie:  [False  True False False False False  True  True  True False]


# Pandas Exercises!
Complete the solution code to have a desired output. 





### 6. Combine `ser1` and `ser2` to form a dataframe.

In [ ]:
# Input
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solution 
df = pd.DataFrame({'A': ser1, 'B' : ser2})

# Print
print(df.tail())
print(df.head())


    A   B
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25
   A  B
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4



### 7. Check if `df` has any missing values.

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.head())

#any는 하나라도 있는 값 확인

# Solution
print('\nIs there any missing value?:',df.isnull().values.any() )

  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0     

### 8. Create a TimeSeries starting `2022-09-01` and 7 weekends (mondays).

In [ ]:
# Solution
ser = pd.Series(pd.date_range('2022-09-01',periods=7 , freq='W-MON'))
print(ser)  #

0   2022-09-05
1   2022-09-12
2   2022-09-19
3   2022-09-26
4   2022-10-03
5   2022-10-10
6   2022-10-17
dtype: datetime64[ns]


### 9. In `df`, compute the median price of every fruit using grouping function.

In [ ]:
import numpy as np

# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange', 'blueberry', 'melon'] * 5,
                   'rating': np.random.rand(25),
                   'price': np.random.randint(0, 20, 25)})
print(df)

# Solution
df.groupby('fruit').median()['price']


        fruit    rating  price
0       apple  0.070079     10
1      banana  0.831000     19
2      orange  0.332456      9
3   blueberry  0.021708      5
4       melon  0.479628      8
5       apple  0.316388     15
6      banana  0.652367     11
7      orange  0.576856     13
8   blueberry  0.761228     13
9       melon  0.321100     10
10      apple  0.804276      4
11     banana  0.526136      3
12     orange  0.647192      9
13  blueberry  0.383598     17
14      melon  0.877848     10
15      apple  0.589514      2
16     banana  0.666611      6
17     orange  0.675952      7
18  blueberry  0.403868     17
19      melon  0.652751      6
20      apple  0.508455      1
21     banana  0.067455      6
22     orange  0.198829     13
23  blueberry  0.664016      8
24      melon  0.342805      9


fruit
apple         4.0
banana        6.0
blueberry    13.0
melon         9.0
orange        9.0
Name: price, dtype: float64

### 10. Join two dataframes `df1` and `df2` for intersection items on `use_id`.
For `df2`, please select only `use_id`, `platform`, `device` columns not all columns for merging.

In [ ]:
# Input
base_path = 'https://raw.githubusercontent.com/shanealynn/Pandas-Merge-Tutorial/master/'
df1 = pd.read_csv(base_path + 'user_usage.csv')
df2 = pd.read_csv(base_path + 'user_device.csv')

# Solution
pd.merge(df1,df2[['use_id','platform','device']],on='use_id').head()

outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id  \
0                    21.97                    4.82     1557.33   22787   
1                  1710.08                  136.88     7267.55   22788   
2                  1710.08                  136.88     7267.55   22789   
3                    94.46                   35.17      519.12   22790   
4                    71.59                   79.26     1557.33   22792   

  platform    device  
0  android  GT-I9505  
1  android  SM-G930F  
2  android  SM-G930F  
3  android     D2303  
4  android  SM-G361F

## TODO! Analyze [Titanic](https://www.kaggle.com/c/titanic) Data
#### (until 21th Sep 2022)



### 0. Data load

In [187]:
import seaborn as sns

# Input
df = sns.load_dataset("titanic")

### 1. Show the first five samples of DataFrame 

In [188]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### 2. Print a concise summary of a DataFrame.
Column names, missing values for each column, and data type for each column.

In [189]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


### 3. Generate descriptive statistics.

In [190]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### 4. Check the number of missing samples per each column

In [191]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

### 5. Return a Series containing counts of unique values on `class` column.

In [192]:
df['class'].value_counts().sort_index()

First     216
Second    184
Third     491
Name: class, dtype: int64

### 6. Calculate the mean of `fare` according to `class` and `sex`
(hint, us `df.groupby`)

In [193]:
df.groupby(['class','sex']).mean()['fare']

class   sex   
First   female    106.125798
        male       67.226127
Second  female     21.970121
        male       19.741782
Third   female     16.118810
        male       12.661633
Name: fare, dtype: float64

### 7. Do same thing by using `df.pivot_table`

In [ ]:
df.groupby(['class','sex']).mean()
df.pivot_table()

pd.pivot_table(df)

KeyError: ignored